@startuml
title Rest API and Messaging flow
autonumber
actor User
participant Frontend
participant Producer
entity MessageBroker
participant Consumer

== Demonstrate how to use REST API with POST method and publish message event to message broker ==

User -> Frontend: /send-data
Frontend -> Producer: POST Product with REST API
Producer -> MessageBroker: PUBLISH product event
Producer --> Frontend: Return simple OK
Frontend --> User: Return simple OK

== Demonstrate how to consume message from message broker and save it to database ==

MessageBroker <-- Consumer: CONSUME Product event 
Consumer -> Consumer: INSERT Product to Database

== Demonstrate how to use REST API with GET Method and query data from database ==

User -> Frontend: /get-data
Frontend -> Consumer: GET Product with Rest API
Consumer -> Consumer: SELECT product from Database
Consumer --> Frontend: Receive Response
Frontend --> User: return response

== Sending another simple Hello message via Message Broker ==

Producer -> MessageBroker: send Hello event
MessageBroker <-- Consumer: CONSUME Hello event

@enduml